### ISSUE TITLE
Extracting the 'trustworthiness' score for an overall genome classification from the output files

### ISSUE THREAD

**Issue by cpauvert** [KIT-IBG-5/mdmcleaner#31]
Hi,
Thanks for developing this tool! After exploring the (many) output files and their columns, I was under the impression that the 'trustworthiness' score (from 0 to 10) mentioned in the [NAR](https://doi.org/10.1093/nar/gkac294) paper was in fact the column `trust_index` in the output file `fullcontiginfos_beforecleanup.tsv`. But this score is currently for each contig. Unfortunately, I could not find the aggregated score at the scale of the overall genome (as mentioned in the paper).

Should it be the _fraction_evaluate_high_ or the _bin_trust_ columns from the file ``overview_all_before_cleanup.tsv`` ? Can you please point future and current users to the equivalent to use :)

Best, 
cpauvert
PS: Maybe this issue is related to #5 ; )

**Comment by jvollme** [comment]
Hi cpauvert,

thanks for your interest in the tool! And yes, this is definitively due to the overloaded output files. I will urgently need to simplify them as soon as my current schedule is a it less full.

The trustworthiness score was primarily actually meant to be for each contig individually, in order to help you in case you want to manually refine the bin yourself. This is what you find in ```fullcontiginfos_before_cleanup.tsv``` in the results-subfolder of each individual bin and tells you for which contig how strongly it agrees or disagrees with the consensus classification of the bin (or whether it could not be cleary clasified at all).

However, the tools indeed also calculates the average trust-score of each bin based on the respective individual contig trust-scores. This is indeed found under "bin_trust" in ```overview_all_before_cleanup.tsv```, as you suspected. Please keep in mind though: A low bin_trust here does NOT necessarily mean that your bin is of low quality! Rather, it can mean that your bin corresponds to a very novel organism with very little reference data (so most interesting but also most difficult to verify).

If you want to see exactly how contaminated your bin was, you should look at the value "fraction_delete". This tells you what fraction (between 0-1. multiply it by 100 to get actual percentage) could be unambigeously identified as contamination. Here also keep in mind please: If this value is very high, you should discard the bin. MDMcleaner was designed to identify, validate and improve good bins, not to rescue bad/highly contaminated bins.

If this does not resolve your question, please don't hesitate to ask further.

**Comment by cpauvert** [comment]
Hi @jvollme,
thanks for your quick and thorough reply! This helps a lot : )
I keep your warnings regarding scores in mind.
Best,
