### ISSUE TITLE
release tag 0.8.3 miss cutofftable_combined.tsv

### ISSUE THREAD

**Issue by EricDeveaud** [KIT-IBG-5/mdmcleaner#32]
Hello 

after installation of mdmcleaner fro taggedrelease: https://github.com/KIT-IBG-5/mdmcleaner/releases/tag/v0.8.3
and a test run I had the following error: ] No such file or directory: 'xxxx/python3.8/site-packages/mdmcleaner-0.8.3-py3.8.egg/mdmcleaner/hmms/cutofftable_combined.tsv'

I was abble to restore the file ussing commit: https://github.com/KIT-IBG-5/mdmcleaner/commit/e917a07af0e93a11e04c8fe133072d21cfdf3dce

regards

Eric

**Comment by jvollme** [comment]
thanks a lot for raising this! It was excluded from the github repository simply because i had ".tsv" listed in my .gitignore. I fixed it now, and will make a new tagged release soon, when i have addressed some other changes. 
However, the current pypi-repository should not have been affected by this, as far as i can see...
