### ISSUE TITLE
silva url

### ISSUE THREAD

**Issue by aelbehery** [KIT-IBG-5/mdmcleaner#33]
Dear developer,

It seems that the url used for downloading silva "https://www.arb-silva.de/fileadmin/silva_databases/current" present in the "read_gtdb_taxonomy.py" Python script is no longer accessible,. I had to change it in the script to the ftp link: "ftp://arb-silva.de/current".
Now, it's working as expected, but I thought it's useful to share this piece of info with you.

Best,

Ali

**Comment by jvollme** [comment]
hmm, that is weird. I just testet the url, and using wget i can still access it. And since mdmcleaner uses wget for downloads of reference data, this should work in mdmcleaner also...

could you provide a detailed error log, so i can better understand what is happening?

**Comment by aelbehery** [comment]
I didn't keep the log unfortunately, but basically it complained from the absence of VERSION.txt.
It seems there has been something wrong with this url, but now when I used  wget https://www.arb-silva.de/fileadmin/silva_databases/current/VERSION.txt and it worked with no problem. Anyway, the inclusion of the ftp link as a backup won't harm ig.

**Comment by jvollme** [comment]
>  Anyway, the inclusion of the ftp link as a backup won't harm ig.

That is true. I will add it as an second option whenever the other url fails. Will then be part of the next tagged release

**Comment by aelbehery** [comment]
Hello John,

Thanks. I have a question not related to this issue. I saw in your NAR
article a comparison between bin contamination calculated by checkm vs that
calculated by mdmcleaner, but when I used mdmcleaner clean command, I
couldn't find the contamination % value. May I know where I can find it? Or
if it's not available, how I can calculate it?

I really appreciate your help and cooperation.

Best regards,

Ali

**Comment by jvollme** [comment]
hi, sorry the output tables are still a bit overcrowdd and confusing.
Contamination estimates from mdmcleaner are best indicated by the "fraction delete" column. Please note though, this gives the fraction of deleted contigs compared to the total contigs as a value between 0 and 1. So in order to get the percentage, you would have to multiply by 100. 
ALso any potential contaminations hidden in any unresolved "reference databse ambiguities" are not factored in there yet also.

I will simplify the result tables soon.

**Comment by aelbehery** [comment]
Thanks for your explanation.
