### ISSUE TITLE
failure to make reference database

### ISSUE THREAD

**Issue by Yunliang81** [KIT-IBG-5/mdmcleaner#51]
Thanks a lot for your contribution to MDMcleaner.

I got an issue with "mdmcleaner mkdb",  the error is  no MD5SUM,  please see the following screenshot.
![image](https://user-images.githubusercontent.com/49252749/208694678-a7e37b16-45d7-428f-a40f-ea50430ab499.png)

Could please help me figure it out?

Thanks,
Peter

**Comment by jvollme** [comment]
Unfortunately the file naming of the MD5 checksum-files are not consistent between gtdb database updates on the gtdb server that mdmcleaner is using to build its database. In the past release it was simply called "MD5SUM". Now it is called "MD5SUM.txt".
Will make a quick fix soon.
Thanks for bringing this to my attention!

**Comment by jvollme** [comment]
problem is fixed now. The problem were changes in the way the gtdb and ncbi refseq databases were organized and the code had to be adjusted to those changes. The fixed version is not, however, yet available on conda or pypi, because I want to implement some other fixes first and don't want to spam those repositories with too many minor version updates...
So for now, you will have to follow the instructions for installing the newest version directly from this repository

**Comment by Yunliang81** [comment]
Hi John,

Thank you very much for your help.

Happy holidays,
Yunliang

JohnVollmers ***@***.***> 于2022年12月28日周三 16:55写道：
